-- Yeni widget tipleri (schema.prisma ile uyumlu)
ALTER TYPE "WidgetTipi" ADD VALUE IF NOT EXISTS 'BASLIK_METIN';
ALTER TYPE "WidgetTipi" ADD VALUE IF NOT EXISTS 'BASLIK_METIN_GORSEL';
ALTER TYPE "WidgetTipi" ADD VALUE IF NOT EXISTS 'BLOG_KARUSEL';
ALTER TYPE "WidgetTipi" ADD VALUE IF NOT EXISTS 'LINK_KARTLARI';
ALTER TYPE "WidgetTipi" ADD VALUE IF NOT EXISTS 'GORSEL_GRID_BLOK';
ALTER TYPE "WidgetTipi" ADD VALUE IF NOT EXISTS 'GORSEL_ETIKET_KARTLARI';
ALTER TYPE "WidgetTipi" ADD VALUE IF NOT EXISTS 'EKIP_KARUSEL';
ALTER TYPE "WidgetTipi" ADD VALUE IF NOT EXISTS 'SAYAC_BLOK';
ALTER TYPE "WidgetTipi" ADD VALUE IF NOT EXISTS 'YORUM_KARUSEL';
ALTER TYPE "WidgetTipi" ADD VALUE IF NOT EXISTS 'FIYATLANDIRMA';
