ALTER TYPE "WidgetTipi" ADD VALUE IF NOT EXISTS 'ZAMAN_CIZELGESI';
ALTER TYPE "WidgetTipi" ADD VALUE IF NOT EXISTS 'SUREC_ADIMLARI';
ALTER TYPE "WidgetTipi" ADD VALUE IF NOT EXISTS 'MARKA_SERIDI';
ALTER TYPE "WidgetTipi" ADD VALUE IF NOT EXISTS 'KARSILASTIRMA_TABLOSU';
ALTER TYPE "WidgetTipi" ADD VALUE IF NOT EXISTS 'GERI_SAYIM';
ALTER TYPE "WidgetTipi" ADD VALUE IF NOT EXISTS 'VIDEO_BANNER';
ALTER TYPE "WidgetTipi" ADD VALUE IF NOT EXISTS 'ONCESI_SONRASI';
ALTER TYPE "WidgetTipi" ADD VALUE IF NOT EXISTS 'BULTEN_KAYIT';
